name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run JVM tests
      run: ./gradlew test
    - name: Build debug app
      run: ./gradlew assembleDebug
    - name: Upload debug build
      uses: actions/upload-artifact@v2.2.3
      with:
        name: debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
